# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "I", "N", "UP", "B", "C4", "D", "PL", "RUF"]

# Exclude commonly ignored directories.
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "build",
    "dist",
]

# Line length
line-length = 88

# Target Python version
target-version = "py38"

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Ignore F401 (unused import) violations in `__init__.py` files
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

# Configure isort
[tool.ruff.isort]
known-first-party = ["local_env_setup"] 