name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      run: |
        pip install poetry
        
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        
    - name: Install dependencies
      run: |
        poetry install
        # Install the package in development mode
        pip install -e .
        
    - name: Run tests
      run: |
        poetry run pytest
        
    - name: Build and publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry build
        poetry publish --username __token__ --password $PYPI_TOKEN 